version: 1.0.{build}
image: Visual Studio 2019
install:
  - "powershell ./install-opengl.ps1"
build_script:
  - cmd: dotnet run --project Test2\OpenTKTest.csproj
test: off
artifacts:
- path: Test.png
on_finish:
  - "powershell ./install-opengl.ps1 uninstall"