# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

jobs:
- job: Build
  strategy:
    matrix:
      windotnet31:
        os: 'windows-latest'
        dotnet: '3.1.100'
      linuxdotnet31:
        os: 'ubuntu-latest'
        dotnet: '3.1.100'
      windotnet30:
        os: 'windows-latest'
        dotnet: '3.0.101'
      linuxdotnet30:
        os: 'ubuntu-latest'
        dotnet: '3.0.101'

  pool:
    vmImage: $(os)

  steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: './install-opengl.ps1'

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(dotnet)

    - task: DotNetCoreCLI@2
      displayName: 'dotnet run 2'
      inputs:
        command: run
        projects: 'Test2\OpenTKTest.csproj'
        workingDirectory: Test2

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: Test2/Test.png

    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: './install-opengl.ps1'
        arguments: uninstall